### ISSUE TITLE
suggestions for business models

### ISSUE THREAD

**Issue by howy1993** [FEMBusinessModelsRing/web3_revenue_primitives#4]
Not sure how to format them so i'll submit them here:

1. (When PoS hits) Sell coins for staked eth. instead of an ICO, ETH is commited for t time in a smart contract to receive x _coins. _coin company receives rewards from staking instead of the ETH itself. after t time, funds are released back to original owners. Pros: Feels more sustainable. Also, users "aren't risking anything" when supporting projects because they don't lose their capital. Cons: can't think of any right now tbh, maybe "PoS is not out yet"?

2. Tips from inflation. For a smaller project (1-2 part time/full time devs). Tokens are minted to the author annually (or some other time period) for upkeeping/upgrading the protocol. This minting could be directly coded into the protocol, could include fancy bells and whistles such as "community votes for 10% 15% or 20% tip" etc. Pros: Model makes a lot of sense. Work put into the protocol should receive rewards from the protocol itself. Cons: Likely not sufficient revenue for a project with >2 employees

**Comment by owocki** [comment]
@howy1993 can you please submit a PR to the repo that puts this info into the readme?

**Comment by owocki** [comment]
@howy1993 are you still interested in contributing?

**Comment by howy1993** [comment]
> @howy1993 are you still interested in contributing?

hey Kevin I'll be happy to! if this is re: the ideas here, i already submitted a PR updating the readme with some ideas to the FEMBusinessModelsRing repo. Otherwise let me know how I could help!

**Comment by owocki** [comment]
mind linking me to the PR? i'm having a hard time finding it :/

**Comment by howy1993** [comment]
jesus, i fucked up and did a PR on the my fork of the repo... thanks for following up. submitting a PR now
