### ISSUE TITLE
Gambling dApps like ETHCrash

### ISSUE THREAD

**Issue by owocki** [FEMBusinessModelsRing/web3_revenue_primitives#44]

**Comment by Anish-Agnihotri** [comment]
I'd be up to add stuff in here, lol. I think I've played enough ETHCrash to have experience.

**Comment by owocki** [comment]
you played ETHCrash? cool!

**Comment by Anish-Agnihotri** [comment]
Yeah! Loved the old ETHCrash. Played a little on the new one too ([EtherCrash](https://www.ethercrash.io/)), but just for fun.

I'll write up some content on how they work, business model, etc. tomorrow and drop it in here for a review.

**Comment by Anish-Agnihotri** [comment]
Closing issue since PR merged. Beginning on next issue. Will convert to website at end, to ensure content consistency across forks.
